import React from 'react';
import { Sparkles, Brain, CheckCircle2, AlertTriangle, ArrowRight, ShieldCheck, Stethoscope, Lightbulb } from 'lucide-react';
import { parseBoldText } from '../utils/textFormatter';

export default function GeminiConsultationCard({ consultation }) {
  if (!consultation) return null;

  const { summary, visualObservations = [], nextSteps = [], ingredientsToAvoid = [] } = consultation;

  return (
    <div className="w-full glass-panel-glow rounded-3xl p-6 sm:p-8 mb-8 border border-cyan-500/40 relative overflow-hidden">
      
      {/* Background Accent Glow */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20"></div>

      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-800/80 relative z-10">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400 shadow-lg shadow-cyan-500/10">
            <Brain className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <h3 className="font-display font-bold text-xl text-white">Gemini 1.5/2.5 Flash Clinical Consultation</h3>
              <span className="px-2.5 py-0.5 rounded-full bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 text-[10px] uppercase font-bold tracking-wider flex items-center space-x-1">
                <Sparkles className="w-3 h-3 text-cyan-400 animate-pulse" />
                <span>Multimodal AI Vision</span>
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Personalized dermatological guidance generated by analyzing your facial image & YouCam AI diagnostics
            </p>
          </div>
        </div>
      </div>

      {/* Summary Box */}
      {summary && (
        <div className="mt-6 p-5 rounded-2xl bg-gradient-to-r from-slate-900/90 to-cyan-950/30 border border-cyan-500/20 relative z-10">
          <div className="flex items-start space-x-3">
            <Stethoscope className="w-5 h-5 text-cyan-400 shrink-0 mt-0.5" />
            <div className="text-sm text-slate-200 leading-relaxed font-medium">
              {parseBoldText(summary)}
            </div>
          </div>
        </div>
      )}

      {/* Grid: Visual Findings & What To Do Next */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6 relative z-10">
        
        {/* Left Column: Visual AI Observations */}
        {visualObservations.length > 0 && (
          <div className="glass-panel rounded-2xl p-5 border border-slate-800/90 flex flex-col justify-between">
            <div>
              <div className="flex items-center space-x-2 pb-3 mb-3 border-b border-slate-800">
                <Lightbulb className="w-4 h-4 text-amber-400" />
                <h4 className="font-bold text-sm text-white">Multimodal Vision Key Findings</h4>
              </div>
              <ul className="space-y-3 text-xs text-slate-300">
                {visualObservations.map((obs, idx) => (
                  <li key={idx} className="flex items-start space-x-2.5">
                    <span className="w-5 h-5 rounded-full bg-slate-900 border border-slate-800 text-cyan-400 font-bold text-[10px] flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <div className="leading-relaxed">{parseBoldText(obs)}</div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Right Column: What To Do Next (Actionable Plan) */}
        {nextSteps.length > 0 && (
          <div className="glass-panel rounded-2xl p-5 border border-teal-500/30 bg-teal-500/5 flex flex-col justify-between">
            <div>
              <div className="flex items-center space-x-2 pb-3 mb-3 border-b border-slate-800">
                <CheckCircle2 className="w-4 h-4 text-teal-400" />
                <h4 className="font-bold text-sm text-white">What To Do Next (Step-by-Step Plan)</h4>
              </div>
              <ul className="space-y-3 text-xs text-slate-200">
                {nextSteps.map((step, idx) => (
                  <li key={idx} className="flex items-start space-x-2.5 p-2.5 rounded-xl bg-slate-900/60 border border-slate-800/80">
                    <ArrowRight className="w-4 h-4 text-teal-400 shrink-0 mt-0.5" />
                    <div className="font-medium leading-relaxed">{parseBoldText(step)}</div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      </div>

      {/* Bottom Row: Ingredients & Habits To Avoid */}
      {ingredientsToAvoid.length > 0 && (
        <div className="mt-6 p-4 rounded-2xl bg-rose-500/5 border border-rose-500/20 relative z-10">
          <div className="flex items-center space-x-2 mb-2 text-rose-300 font-semibold text-xs uppercase tracking-wider">
            <AlertTriangle className="w-4 h-4 text-rose-400" />
            <span>Ingredients & Habits To Avoid Immediately</span>
          </div>
          <div className="flex flex-wrap gap-2 pt-1">
            {ingredientsToAvoid.map((item, idx) => (
              <span key={idx} className="px-3 py-1.5 rounded-xl bg-rose-500/10 border border-rose-500/30 text-xs font-medium text-rose-200">
                🚫 {parseBoldText(item)}
              </span>
            ))}
          </div>
        </div>
      )}

    </div>
  );
}

